project:
  type: book

  

book:
  title: "Formes Modulars"
  subtitle: "Un introducció a la cinquena operació bàsica"
  author: "Marc Masdeu"

  date: "2/5/2024"
  chapters:
    - index.qmd
    - dia1.qmd
    - dia2.qmd
    - dia3.qmd
    - dia4.qmd
    - bibliografia.qmd
  sidebar:
    pinned: true
  repo-url: https://www.github.com/mmasdeu/formesmodulars   
  issue-url: https://www.github.com/mmasdeu/formesmodulars/issues
  repo-actions: [edit, issue, source]
  search: 
    location: sidebar
    type: textbox
  downloads: [pdf]

bibliography: references.bib

format:
  html:
    lang: ca
    language:
      title-block-author-single: "Autor"
    theme: materia

  pdf:
    lang: ca
    documentclass: scrreprt
    colorlinks: true
    toc: true
    toc-depth: 2
    number-sections: true
    cite-method: biblatex
    

