{{< include macros.qmd >}}

# Primer dia


Abans d'introduir els objects que estudiarem, és natural preguntar-nos per què els estudiem (a més del fet que són objectes matemàtics extremadament bonics).

Resulta que molts problemes en la teoria de nombres (i en altres ciències) tracten de *comptar* certs objectes. Per exemple, podem comptar el nombre de particions d'un enter $n$ (maneres d'obtenir $n$ com a suma de naturals positius ordenats), o el nombre de solucions mòdul $n$ de l'equació $y^2+y=x^3-x^2$, o bé el nombre de maneres d'escriure $n$ com a suma de $2$ quadrats,... Doncs resulta que per tots els problemes anteriors (i molts d'altres) aquests recomptes donen, un cop escrits en forma de sèrie de potències, una forma modular.

El fet anterior ja seria de per si interessant, ja que estudiar formes modulars ens permetria estudiar tots aquests problemes a la vegada. El que és encara més sorprenent és que resulta que les formes modulars constitueixen espais vectorials de dimensió finita, i això fa que si podem construir suficients exemples, podem descobrir identitats sorprenents. Com a mostra, podem enunciar alguns teoremes que aprofiten aquest fet:

::: {#thm-1}
Per a tot primer $p$, es té:
$$
\#\{(x,y)\in\ZZ/p\times\ZZ/p : y^2+y=x^3-x^2\} = p - a_p,
$$
on $a_p$ és el coeficient de $q^p$ de la sèrie formal
$$
q\prod_{n=1}^\infty (1-q^n)^2(1-q^{11n})^2=q-2q^2-q^3+2q^4+q^5+2q^6-2q^7+\cdots.
$$
:::

::: {#thm-fermat}
## Fermat
El nombre de maneres d'escriure $n$ com a suma de $2$ quadrats és

$$
4\sum_{\substack{d\mid n\\d \equiv 1\mod 4}} d - 4\sum_{\substack{d\mid n\\d \equiv 3\mod 4}} d,
$$

on les sumes recorren els divisors $d$ de $n$ positius.
:::

::: {#thm-cubic}
Sigui $a_p$ el nombre d'arrels del polinomi $x^3-x-1$ a $\ZZ/p\ZZ$. Aleshores per tot primer $p\neq 23$, $a_p-1$ és el coeficient de $q^p$ de la sèrie formal
$$
q\prod_{n=1}^\infty (1-q^n)(1-q^{23n}).
$$
:::

::: {#thm-ramanujan}
## Ramanujan
Sigui $\tau(n)$ el coeficient de $q^n$ de la sèrie formal $\Delta(q)=q\prod_{n\geq 1} (1-q^n)^{24}$. Aleshores per a tot $n\geq 1$,
$$
\tau(n) \equiv \sum_{d\mid n} d^{11} \pmod{691}.
$$
:::

## Definicions bàsiques


Considerem el semiplà superior de Poincaré,
$$
\HH = \{z\in \CC : \Im(z) >0\}
$$
i el grup $\operatorname{SL}_2(\mathbb{R})$, definit com
$$
\SL_2(\RR) = \left\{ \smtx abcd \in M_2(\RR) : ad-bc = 1\right\}.
$$

Aquest grup actua en els complexos (de fet, a $\mathbb{C} \cup \{\infty\}$)
mitjançant les anomenades *transformacions lineals fraccionàries*:
$$
g\cdot z =\smtx{a}{b}{c}{d}\cdot z = \frac{az+b}{cz+d}.
$$

Es té una fórmula  senzilla per la part imaginària d'aquesta quantitat:
$$
\Im(gz) = \frac{\Im(z)}{ |cz+d|^2}.
$$

Per tant, veiem que $\operatorname{SL}_2(\mathbb{R})$ actua a $\mathbb{H}$. Com que $-1$ actua trivialment, de fet tenim una acció del quocient $\PSL_2(\RR) = \SL_2(\RR)/\{\pm 1\}$, que de fet és *fidel*.

::: {#rem-}
De fet, el grup $\PSL_2(\RR)$ és el grup d'automorfismes analítics d'$\HH$.
:::

::: {#def-grup-modular}
El grup $G = \PSL_2(\RR)$ s'anomena el *grup modular*. Sovint confondrem una matriu $g = \smtx abcd$ amb la seva imatge a $G$.
:::

## El domini fonamental

Considerem dos elements a $G$ que jugaran un paper important:
$$
S = \smtx{0}{-1}{1}{0},\quad T = \smtx 1101.
$$
Actuen enviant $z$ a $S z=-1/z$ i $T z = z+1$. A més, satisfan les relacions (a $G$)
$$
S^2=1,\quad (ST)^3=1.
$$
Considerem ara el conjunt $D\subseteq \HH$ definit com
$$
D = \{ z \in \HH : |\Re(z)|\leq 1/2, |z| \geq 1 \}.
$$
Es té el següent:


::: {#thm-fundom}
1. Per cada $z\in\HH$ hi ha algun $g\in G$ tal que $gz\in D$.
#. Siguin $z, z'\in D$ congruents mòdul $G$. Aleshores o bé $\Re(z)=\pm 1/2$ i $z=z'\pm 1$, o bé $|z| = 1$ i $z'=-1/z$.
#. Sigui $z\in D$, i considerem $G_z=\{g \in G: g z = z\}$. Aleshores $G_z=1$ excepte si:

   a. $z=i$, i aleshores $G_i = \{1, S\}$.
   #. $z = \rho=e^{2\pi i/3}$, i aleshores $G_\rho=\{1, ST, (ST)^2\}$.
   #. $z = -\bar\rho=e^{\pi i /3}$, i aleshores $G_{-\bar\rho}=\{1, (TS), (TS)^2\}$.

#. El grup $G$ està generat per $S$ i $T$. De fet, es té $G=\langle S, T | S^2=(ST)^3=1 \rangle$.
:::

:::{#proof}
Considerem $G'=\langle S, T\rangle$. Donat $z\in\HH$, trobarem $g'\in G'$ tal que $g'z\in D$. Escrivim $g=\smtx abcd$ un element de $G'$ arbitrari, i observem que hi ha un nombre finit de parelles $(c,d)$ tals que $|cz+d|<M$ (per qualsevol $M$ fixat): si escrivim $z=x+iy$, aleshores $|cz+d|>|cx+d|$ i $|cz+d|>|cy|$ i, per tant, hi ha un nombre finit de $c$ i de $d$ que el fan més petit. Aleshores per la fórmula
$$
\Im(gz)=\frac{\Im(z)}{|cz+d|^2}
$$
veiem que hi ha algun $g\in G'$ que maximitza $\Im(gz)$. Triem ara $n\in\ZZ$ tal que $T^ngz$ tingui part real entre $-1/2$ i $1/2$. Aleshores és fàcil veure que $z'=T^ngz$ és a $D$ (si no ho fos, seria perquè $|z'|<1$, però aleshores $-1/z'$ tindria part imaginària més gran, contradicció).

Per demostrar el segon punt, suposem que $z$ i $gz$ pertanyen a $D$. Per simetria, podem assumir que $\Im(gz)\geq \Im(z)$, és a dir,
$$
|cz+d|^2=(cx+d)^2 + (cy)^2\leq 1, \quad z=x+iy.
$$
Com que $y^2 \geq 3/4$, això implica que $|c|\leq 1$. Analitzant els diferents casos $c=0$, $c=1$ i $c=-1$ obtenim el que quedava per demostrar, excepte el fet que $G=G'$.

Sigui ara $g\in G$ un element arbitrari, i prenem $z_0$ a l'interior de $D$. Considerem $z=gz_0$, i trobarem $g'\in G'$ tal que $g'z$ pertanyi a $D$. Pel què hem vist $g'z=z_0$ i d'aquí obtenim $g'g=1$, i per tant $g$ pertany a $G'$.
:::

::: {#cor-}
L'aplicació de pas al quocient $D \to \HH/G$ és exhaustiva, i la seva restricció a l'interior de $D$ és injectiva.
:::


## Formes modulars


### Definicions


::: {#def-debilment-modular}
Diem que una funció $f$ meromorfa a $\HH$ és *dèbilment modular* de pes $k\in\ZZ$ si
$$
f(g z) = (cz+d)^k f(z),\forall g=\smtx abcd \in\SL_2(\ZZ).
$$
:::

És convenient introduir aquí la notació "slash": definim $f \slsh{k} g$ com la funció (que depèn de $k$, encara que no ho posem a la notació)
$$
(f \slsh{k} g)(z) = (cz+d)^{-k} f(z).
$$
Aleshores veiem que $f$ és dèbilment modular si, i només si, $f\slsh{k} g=f$ per a tot $g\in \SL_2(\ZZ)$.

Com que $G$ està generat pels elements $S$ i $T$, aquesta condició és equivalent a demanar que, per a tot $z\in \HH$,
$$
f(z+1)=f(z),\quad f(-1/z) = z^{k}f(z).
$$

::: {#rem-} 
Aplicant la definició a $-1\in \SL_2(\ZZ)$ obtenim que $f(z)=(-1)^k f(z)$. Per tant, si $k$ és senar només la funció $0$ és dèbilment modular. Demanarem doncs, d'aquí en endavant, que $k$ sigui parell.
:::

Fixem-nos que, si $f(z+1)=f(z)$ per a tot $z\in \HH$, aleshores podem composar amb el canvi $q=e^{2\pi i z}$ i obtenir una funció $\tilde f(q)$ definida a

$$
\tilde{\HH}=\{q\in \CC : 0 < |q| < 1 \}.
$$
Aleshores, $\tilde f$ tindrà una sèrie de Laurent al voltant de $q=0$:
$$
\tilde f(q) = \sum_{n=-\infty}^\infty a_nq^n.
$$
Direm aleshores que $f$ és *meromorfa a l'infinit* si $\tilde f$ és meromorfa a $q=0$ ($a_n=0$ per $n<<0$). També direm que $f$ és *holomorfa a l'infinit* si $a_n=0$ per $n < 0$, i $f$ s'anul·la a l'infinit si $a_n=0$ per $n\leq 0$.

::: {#def-forma-modular}
Una *forma modular* de pes $k$ és una funció dèbilment modular que és holomorfa a tot arreu, incloent l'infinit. Si aquesta s'anula a l'infinit, l'anomenarem una *forma cuspidal*. Denotem per $M_k$ el $\CC$-espai vectorial de les formes modulars de pes $k$, i per $S_k\subseteq M_k$ el subespai de les formes cuspidals.

:::
Resumint, una forma modular de pes $k$ ve donada per una sèrie
$$
f(z) = \sum_{n=0}^\infty a_n q^n = \sum_{n=0}^\infty a_ne^{2\pi i nz},
$$
que convergeix per a tot $z\in \HH$, i que satisfà $f(-1/z) = z^kf(z)$.

::: {#rem-} 
Si multipliquem una forma modular $f$ de pes $k$ amb una $f'$ de pes $k'$ obtindrem una forma $ff'$ de pes $k+k'$. Obtenim així un anell graduat $M=\bigoplus_{k\in\ZZ} M_k$.
:::


### Sèries d'Eisenstein

Per ara els únics exemples que tenim de formes modulars són les constants, que són formes modulars de pes zero (de fet, són les úniques formes modulars de pes zero). Si considerem una funció holomorfa $h$ qualsevol, aleshores una manera de construir una funció modular és "simetritzar-la", és a dir, considerar $\sum_{g\in G} h\slsh{k} g$. El problema és que en general aquesta suma no té per què convergir. Una segona idea seria considerar una funció que ja sigui invariant per algun subgrup de $H\leq G$, i aleshores només simetritzar per $G/H$. La versió més senzilla d'aquest principi és considerar la funció constant $1$. Si $H=\{ \pm \smtx{1}{t}{0}{1}\}$, veiem que $1\slsh{k} h=1$ per a tot $h\in H$. Per tant, podem considerar
$$
\tilde G_k(z) = \sum_{\gamma \in H\backslash \SL_2(\ZZ)} 1\slsh{k} \gamma= \sum_{\smtx abcd \in H \backslash \SL_2(\ZZ)} \frac{1}{(cz+d)^{k}}.
$$
Fixem-nos que, donada una matriu $\smtx abcd\in \SL_2(\ZZ)$, la classe lateral $H\smtx abcd$ està formada per totes les matrius de la forma $\smtx{a'}{b'}{c}{d}\in\SL_2(\ZZ)$. És a dir, les classes laterals venen indexades per parelles $(c,d)\in\ZZ^2$ amb $\gcd(c,d)=1$. És més comú considerar totes les parelles diferents de $(0,0)$, i definir
$$
G_k(z) = \sum_{(c,d)\neq (0,0)} \frac{1}{(cz+d)^k}.
$$
La relació entre $G_k$ i $\tilde G_k$ és un factor de $\zeta(k)$ (exercici).

::: {#prp-}
Si $k>2$, la funció $G_k(z)$ és una forma modular de pes $k$. El seu valor a l'infinit és $2\zeta(k)$, on $\zeta$ és la funció zeta de Riemann.
:::

::: {.proof}
Ens cal primer veure la convergència de la sèrie per tot $z$. Considerem primer $z\in D$ fixat, i podem veure fàcilment que $|c z + d|^2 \geq c^2-cd+d^2= |c\rho + d|^2$. Com que
$$
\#\{ (c,d)\neq (0,0) : N \leq |c\rho - d|< N+1\} = O(N)
$$
i $\sum_{n\geq 1} 1/n^{k-1}$ convergeix per $k>2$, ja estem. Com que $D$ és compacte, la sèrie $G_k(z)$ convergeix normalment a $D$ (vol dir que la sèrie de les sup-normes convergeix) i, com que podem traslladar $D$ per recobrir tot $\HH$ amb elements de $\SL_2(\ZZ)$, en deduïm que $G_k(z)$ també convergeix a tot $\HH$ a una funció holomorfa.

Per calcular $G_k(\infty)$, prenem el límit quan $\Im(z)\to\infty$, i això ho podem fer mantenint $z$ a $D$. En aquest cas, gràcies a la convergència uniforme de la sèrie podem prendre el límit terme a terme. Els termes que tenen $c\neq 0$ tots van a $0$, i només ens queda
$$
\lim G_k(z) = \sum_{n\neq 0} n^{-k} = 2 \zeta(k).
$$
:::

Podem normalitzar $G_k$ per tal que prengui el valor $1$ a l'infinit, i obtenim $E_k(z)=\frac{1}{2\zeta(k)} G_k(z)$. Aleshores podem fer combinacions de sèries d'Eisenstein per obtenir altres formes modulars. Per exemple,
$$
\Delta(z) = \frac{E_4^3 - E_6^2}{1728}
$$
és una forma cuspidal de pes $12$, anomenada la funció discriminant (més endavant veurem per què hem dividit per $1728$).

::: {#rem-}
Definim, per $\tau\in\HH$ i $w\in\CC$, la funció $\wp$ de Weierstrass, com
$$
\wp_\tau(w)=\frac{1}{w^2}+\sum_{(c,d)\neq (0,0)} \left(\frac{1}{(w-c\tau-d)^2}-\frac{1}{(c\tau+d)^2}\right).
$$
Aleshores la sèrie de Laurent de $\wp_\tau$ és fàcil de calcular, i resulta que les sèries d'Eisenstein apareixen com a coeficients d'aquesta sèrie:
$$
\wp_\tau(w) = \frac{1}{w^2} + \sum_{k=2}^\infty (2k-1)G_{2k}(\tau)w^{2k-2}.
$$
De fet, si definim $x=\wp_\tau(w)$ i $y=\wp_\tau'(w)$ (la derivada respecte $w$), tenim
$$
y^2=4x^3-60G_4(\tau)x-140G_6(\tau),
$$
que és una corba el·líptica amb discriminant justament $16\Delta(\tau)$, que per tant és diferent de zero.
:::

## L'espai de les formes modulars


### Zeros i pols d'una funció modular

Sigui $f\neq 0$ una funció meromorfa a $\HH$, i sigui $\tau\in\HH$. Escrivim $v_{\tau}(f)$ com l'enter tal que $(z-\tau)^{- v_{\tau}(f)} f(z)$ és holomorfa i diferent de zero a $z=\tau$ (l'ordre de $f$ a $\tau$).

Si $f$ és una funció modular de pes $k$, aleshores $v_\tau(f)=v_{g\tau}(f)$, perquè $cz+d$ és holomorfa i diferent de zero a tot $\HH$. També podem definir $v_\infty(f)=n_0$ si $\tilde f(q)=\sum_{n\geq n_0} a_nq^n$ amb $a_{n_0}\neq 0$.

::: {#thm-valencia}
## fórmula de la valència
Si $f\neq 0$ és una funció dèbilment modular de pes $k$, es té
$$v_{\infty}(f) + \frac{1}{2} v_{i}(f) +\frac{1}{3}v_{\rho}(f) +\sum_{\tau\in G\backslash \HH} v_{\tau}(f) = \frac{k}{12},
$$
on la suma recorre les òrbites de punts de $\HH$ diferents de $i$, $\rho$ i $-\bar\rho$.
:::

::: {#rem-} 
La suma només conté un nombre finit de termes no nuls. En efecte, com que $f$ és meromorfa tenim que $\tilde f$ no té cap zero ni pol al disc $0<|q|<r$ per algun $r >0$. Per tant, $f$ no té zeros ni pols a la regió $\Im(z)>\frac{\log(1/r)}{2\pi}$ i, llavors $f$ té tots els zeros i pols de $D$ a la regió compacta $D\cap \Im(z)< \frac{\log(1/r)}{2\pi}$, on només n'hi pot haver un nombre finit.
:::

El teorema es demostra aplicant el teorema del residu a un contorn adequat, i no el farem en aquestes notes.

### L'àlgebra de formes modulars


Escrivim $M_k$ com el $\CC$-espai vectorial format per les formes modulars de pes $k$, i $S_k$ com el subespai format per les formes cuspidals. Com que $S_k=\ker( f\mapsto f(\infty))$, tenim $\dim M_k/S_k\leq 1$. A més, quan $k\geq 4$ les sèries d'Eisenstein són de $M_k\smallsetminus S_k$ i, per tant $M_k = \CC G_k \oplus S_k$.

Aplicarem la fórmula de la valència a alguns casos senzills. Per exemple, si $f$ és una funció holomorfa, aleshores tots els termes que apareixen a l'esquerra són positius o zero, i per tant $M_k=0$ per $k<0$. Per $k=2$, veiem que no hi ha manera d'obtenir $1/6$ sumant múltiples de $1$, $1/2$ i $1/3$, i per tant $M_2=0$.

Ara, apliquem la fórmula a $G_4$. Podem escriure $1/3 = 0 + 1/2\cdot 0 + 1/3\cdot 1+0$ (i només d'aquesta manera), i per tant $G_4(\rho)=0$ (amb ordre $1$), i no s'anul·la enlloc més. De forma semblant, $v_{i}(G_6) = 1$ i aquest és l'únic punt on s'anul·la $G_6$. Observem llavors que $\Delta(i)\neq 0$ i que, per tant $\Delta\neq 0$. A més, per construcció $v_{\infty}(\Delta)\geq 1$. Per tant, la fórmula de la valència ens diu que $\Delta$ no s'anul·la a $\HH$, i té un zero simple a l'infinit.

Finalment, sigui $f$ un element de $S_k$, i definim $g=f/\Delta$. Aleshores $g$ té pes $k-12$, i $v_{\tau}(g)\geq 0$ per a tot $\tau$. Per tant $g\in M_{k-12}$.

Podem acabar calculant per $k\leq 10$ els espais $M_k$. En aquest cas, $k-12 < 0$ i $S_k=0$. Per tant, $\dim M_k\leq 1$. Com que $1, G_4, G_6, G_8, G_{10}$ són elements de $M_k$ per $k=0, 4,6,8,10$, formen una base de l'espai corresponent.

Resumim el què hem demostrat:

::: {#thm-Mk}
1. $M_k=0$ per $k<0$ i $k=2$.
2. $M_0=\CC\cdot 1$, $M_4=\CC\cdot G_4$, $M_6=\CC\cdot G_6$, $M_8=\CC\cdot G_8$ i $M_{10} = \CC\cdot G_{10}$. En aquests casos, $S_k=0$.
3. La multiplicació per $\Delta$ indueix un isomorfisme $M_{k-12}\cong S_k$.

En particular, $\dim M_k=\lfloor k/12\rfloor$ si $k\equiv 2 \pmod{12}$, i $\dim M_k=\lfloor k/12\rfloor +1$ si $k\neq 2\pmod{12}$.
:::

::: {#cor-}
L'espai $M_k$ té com a base el conjunt de monomis $G_4^iG_6^j$, on $i,j\geq 0$ són enters amb $4i+6j=k$.
:::

::: {.proof}
Veiem primer que generen, cosa que és clara per $k\leq 6$. Per $k\geq 8$, fem inducció en $k$. Triem enters positius $i,j$ tals que $4i+6j=k$, i considerem $g =G_4^iG_6^j$, que no s'anula a l'infinit. Si $f\in M_k$, aleshores $f-\lambda g\in S_k$ per algun $\lambda\in\CC$. Per aquest $\lambda$, tenim $f-\lambda g = \Delta h$ amb $h\in M_{k-12}$. Apliquem ara la hipòtesi d'inducció a $h$, i ja estem.

Si aquests monomis no fossin linealment independents, la funció $G_4^3/G_6^2$ satisfaria un polinomi amb coeficients a $\CC$ i, per tant, seria constant. Però això no pot ser, perquè $G_4$ s'anula a $\rho$ i $G_6$ no, per exemple.$\qed$
:::

::: {#rem-} 
Es pot resumir l'anterior dient que $M=\bigoplus_{k\in\ZZ} M_k \cong \CC[G_4,G_6]$.
:::

